---
title: ''
author: "Xiao Liu, LE Lee, and Paul Hunt"
date: "11/14/2021"
output: 
  pdf_document:
    extra_dependencies: ["flafter"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, echo = F,
                      message = F, warning = F,
                      fig.align = "center")
library(ggplot2)
library(ggpubr)
library(table1)
library(kableExtra)
library(pander)
library(TSA)
library(lme4)
library(dagitty)
library(lavaan)
library(ggdag)

library(sp)
library(ggmap)
library(stringr)
library(dplyr)
library(ade4)
library(viridis)
library(imputeTS)
library(corrplot)
```



## Introduction

## Data
```{r Data Import and Cleaning}
# Import the Data
data.p3 <- read.csv("otter2.csv", stringsAsFactors = T)

# Create a Seasonal Factor
data.p3$Season <- factor(nrow(data.p3))
levels(data.p3$Season) <- c("Winter", "Spring",
                            "Summer", "Fall")

attach(data.p3)
Season[(Month.1 == 12)|
         (Month.1 ==1)|
         (Month.1 ==2)]   <- "Winter"
Season[(Month.1 == 3)|
         (Month.1 == 4)|
         (Month.1 == 5)]  <- "Spring"
Season[(Month.1 == 6)|
         (Month.1 == 7)|
         (Month.1 == 8)]  <- "Summer"
Season[(Month.1 == 9)|
         (Month.1 == 10)|
         (Month.1 == 11)] <- "Fall"

data.p3$Season <- Season

table1::label(data.p3$Trout)        <- "Trout Population"
table1::label(data.p3$Water.Excess) <- "In-water Excess Activity"
table1::label(data.p3$Land)         <- "Time spent on Land"
table1::label(data.p3$Caloric)      <- "Caloric Expenditure"
table1::label(data.p3$Water)        <- "Water Availability"
```

```{r Generating Table 1 (vars by season)}
table_1.dat <- data.frame(Activity, Altitude,
                          Trout, Season, Caloric,
                          Water.Excess, Land,
                          Water, Amoeba)
t1.season <- table1(~.|Season, data=table_1.dat,
       render.continuous =c(.= "Mean (SD)", .= "[Min, Max]"),
       caption = "Descriptive Statistics of
       Variables by Season")
```

```{r Generating Table 2 (Vars by site)}
table_2.dat <- data.frame(Activity, Altitude,
                          Trout, Site, Caloric,
                          Water.Excess, Land,
                          Water, Amoeba)
t1.site <- table1(~.|Site, data=table_2.dat,
       render.continuous =c(.= "Mean (SD)", .= "[Min, Max]"),
       overall = F,
       caption = "Descriptive Statistics of
       Variables by Capture Site")
```

### Missing Values
```{r}
otters <- data.p3 %>% mutate(Date = as.Date(paste(Year,Month.1,"01",sep="-")))
# MAR data - LOCF Imputation
# Include in technical report: Why is LOCF appropriate & why are we doing it?
otters <- otters %>% mutate(Trout = na_locf(Trout), Altitude = na_locf(Altitude))
# MNAR data - zero
otters <- otters %>% mutate(Amoeba = replace(Amoeba, which(is.na(Amoeba)), min(na.omit(Amoeba))-0.5), Water = replace(Water, which(is.na(Water)), 0))
```



## Exploratory Data Analysis

### Otter Activity

```{r Dependent Variable, fig.cap="Here we have plotted the change in activity at the five sites in the months since the beginning of the study. The general upward trend for all sites and the potential seasonal variation are more evident in the log-scale."}
gg1.1 <- ggplot(data = otters,
                aes(x = Month, y = Activity, color = Site)) +
  geom_point() +
  geom_smooth(se = F) + labs(x = NULL)

gg1.2 <- ggplot(data = otters,
                aes(x = Month, y = log(Activity), color = Site)) +
  geom_point() +
  geom_smooth(se = F) + labs(x = NULL)

gg1.a <- ggarrange(gg1.1,gg1.2, nrow = 1,
                 common.legend = T,
                 legend = "right")
gg1 <- annotate_figure(gg1.a,
                bottom = text_grob("Months since Beginning of Study", size = 11),
                top = "Changes in Activity over Time by Site")
gg1
```

```{r Autocorrelation, fig.show="hold", out.height="45%", fig.height=2, fig.cap="The autocorrelation plots of activity measurements at site Alpha show a dependence on time, but not clear seasonal cycles."}
par(mar = c(1,4,2,0.1))
acf(Activity[1:20], main = "Autocorrelation of Activity at Site Alpha",
    xlab = "")
par(mar = c(4,4,0.25,0.1))
pacf(Activity[1:20], main = "")
```

### Predictors







```{r Seasonal effects on predictors, fig.cap="Boxplots of the predictor variables by season show little change between seasons for any of the predictors."}
fig3.1 <- ggplot(otters, aes(fill = Season, y = Altitude)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig3.2 <- ggplot(otters, aes(fill = Season, y = Trout)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig3.3 <- ggplot(otters, aes(fill = Season, y = Caloric)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig3.4 <- ggplot(otters, aes(fill = Season, y = Water.Excess)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig3.5 <- ggplot(otters, aes(fill = Season, y = Amoeba)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig3.6 <- ggplot(otters, aes(fill = Season, y = Land)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig3.7 <- ggplot(otters, aes(fill = Season, y = Water)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

fig3 <- ggarrange(fig3.1, fig3.2, fig3.3, fig3.4, fig3.5, fig3.6, fig3.7,
                  common.legend = T, legend = "right")

annotate_figure(fig3, top = "Predictor Variables by Season")
```

```{r Locational effects on predictors, fig.cap="The boxplots of predictor variables by location show meaningful differences between altitude, trout population, and amoeba prescence between the five locations."}
fig4.1 <- ggplot(otters, aes(fill = Site, y = Altitude)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig4.2 <- ggplot(otters, aes(fill = Site, y = Trout)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig4.3 <- ggplot(otters, aes(fill = Site, y = Caloric)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig4.4 <- ggplot(otters, aes(fill = Site, y = Water.Excess)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig4.5 <- ggplot(otters, aes(fill = Site, y = Amoeba)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig4.6 <- ggplot(otters, aes(fill = Site, y = Land)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
fig4.7 <- ggplot(otters, aes(fill = Site, y = Water)) + geom_boxplot() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

fig4 <- ggarrange(fig4.1, fig4.2, fig4.3, fig4.4, fig4.5, fig4.6, fig4.7,
                  common.legend = T, legend = "right")

annotate_figure(fig4, top = "Predictor Variables by Location")
```

### Relationships between Predictors

```{r Correlletions with P-vals}
cor.mat <- function(X){
  tbl <- matrix(numeric(ncol(X)^2),
                ncol = ncol(X),
                nrow = ncol(X))
  row.names(tbl) <- colnames(X)
  colnames(tbl)  <- colnames(X)
  
  for(i in 1:ncol(X)){
    for(j in i:ncol(X)){
      tbl[j,i] <- round(cor.test(X[,i], X[,j])$p.value, 3)
      tbl[i,j] <- round(cor(X[,i], X[,j]), 3)
    }
  }
  tbl <- as.table(tbl)
  diag(tbl) <- ""
  tbl
}

colin <- cor.mat(otters[,sapply(otters, is.numeric)])
colin.tbl <- colin %>% kbl(digits = 3, booktabs = T,
                           caption = "Covariates with correlation coefficients in the upper triangle and p-values in the lower triangle") %>%
  kable_classic() %>% kable_styling(font_size = 9)
```

```{r Scatterplot Matrix, fig.cap = "Here we have included the predictor variables with clear and potential co-linearity in a scatterplot matrix with correlation coefficients in the upper triangle. Of particular concern is the nearly perfect inverse relationship between time on land and in water, and the strong relationship between those two variables and caloric expenditure."}

panel.cor <- function(x, y, ...)
{
par(usr = c(0, 1, 0, 1))
txt <- as.character(format(cor(x, y), digits=2))
text(0.5, 0.5, txt)
}
pairs(otters[,c("Altitude", "Amoeba", "Trout", "Caloric", "Land", "Water")],
      main = "Scatterplot of Variables Exhibiting Co-linearity",
      col = "blue", pch = 19, cex =0.85,
      upper.panel = panel.cor)

```


## Model Specification

### Theoretical Model

```{r, fig.cap="Our hypothesized structure implies that the information contained in Site and calories are included in the other variables, and do not need to be included in the final model. Additionally, land and water activity inform each other, so only one should be included."}
CI.graph <- dagitty('dag {
Site        [pos="3,4"]
Alt.        [pos="3,2"]
Cal.        [pos="4,2"]
Trout       [pos="3.5,3"]
W.E.        [pos="5,2"]
Amb.        [pos="3.5,1"]
Land        [pos="1,2"]
Water       [pos="2,2"]
Activity    [pos="3,0"]

Site -> Alt.
Site -> Trout
Site -> W.E.
Site -> Amb.
Site -> Land
Site -> Water
Alt. -> Cal.
Alt. -> Activity
Trout -> Cal.
Trout -> Activity
W.E. -> Cal.
W.E. -> Activity
Amb. -> Cal.
Amb. -> Activity
Land -> Water
Land -> Activity
Water -> Land
Water -> Activity
}')

ggdag(CI.graph) + theme_dag()+geom_dag_node(col = "gray", size=20) +
  geom_dag_text(col = "blue")+geom_dag_edges() +
  ggtitle("Hypothesized Causal Model")
```


### Model Fit
```{r}
lmod_1 <- lmer(log(Activity)~Land+Altitude+Amoeba+Trout+Water.Excess+Season+(Month|Site), data = otters)
lmer_pred <- predict(lmod_1,
                     newdata = otters[,c("Land", "Altitude", "Amoeba",
                                         "Trout", "Water.Excess", "Month", "Season", "Site")])

lmod.mat <- cbind(pred = lmer_pred, otters)

ggplot(lmod.mat, aes(y = pred, x = Date, color = Site)) +
  geom_line() + geom_point(aes(y=log(Activity), x = Date)) +
  scale_x_date(date_labels = "%b %Y")
```

### Model Diagnostics

```{r, fig.cap="The fitted vs. residuals plot for our first model is clearly centered around zero, and there are no obvious patterns."}
plot(lmer_pred, lmer_pred-log(Activity),
     col = rgb(0,0,1, alpha = 0.65),
     pch = 20, cex = 1.5,
     main = "Residuals vs. Fitted Plot",
     ylab = "Residuals",
     xlab = "Fitted")
abline(h=0)
```


## Conclusion

\newpage
## Supplemental Figures
`r t1.season`
`r t1.site`
`r colin.tbl` 














